### ISSUE TITLE
Development branch bug - simple query not working on server.

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#62]
Following [this fix](https://github.com/mynlp/jigg/issues/50), i have reassembled the `develop` branch.

However - running a simple query like the below is returning a `The requested resource could not be found.` error. (no error on the server's standard output)
```
curl --data-urlencode "annotators=corenlp[tokenize,ssplit]" --data 'aaa bbb' "http://localhost:8080/annotate?outputFormat=json"
```

The problem seems restricted to english annotation
```
# Parse - "これは桃" - this works
curl --data-urlencode "annotators=ssplit,mecab" --data '%E3%81%93%E3%82%8C%E3%81%AF%E6%A1%83' "http://localhost:8080/annotate?outputFormat=json"
```

but is not limited to strings - files also fail
```
$ cat en.txt
my name is slim.
this is a car.
$ curl --data-urlencode "annotators=corenlp[tokenize,ssplit]" --data @en.txt "http://localhost:8080/annotate?outputFormat=json"
The requested resource could not be found.
```

One other issue, probably different is that - despite [this solution](https://github.com/mynlp/jigg/issues/57), adding `corenlp[tokenize,ssplit]` as an annotator fails to parse sentences with line breaks.
```
curl --data-urlencode "annotators=corenlp[tokenize,ssplit]" --data 'aaa%0Abbb' "http://localhost:8080/annotate?outputFormat=json"
```
Below is the server log in this case - could this be fixed by ensuring ssplit occurs before tokenize perhaps?
```
[INFO] [02/23/2017 10:58:28.317] [jigg-server-akka.actor.default-dispatcher-4] [akka://jigg-server/user/$a] Pipeline is updated. New property: {annotators=corenlp[tokenize,ssplit]}
[jigg-server-akka.actor.default-dispatcher-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[jigg-server-akka.actor.default-dispatcher-3] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
[jigg-server-akka.actor.default-dispatcher-3] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[ERROR] [02/23/2017 10:58:29.268] [jigg-server-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(jigg-server)] Error during processing of request: 'Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: {".tag":"root",".child":[{".tag":"document","id":"d0",".child":[{".tag":"sentences",".child":[{".tag":"sentence","text":"aaa
bbb","id":"s0","characterOffsetBegin":"0","characterOffsetEnd":"7",".child":[{".tag":"tokens","annotators":"corenlp",".child":[{".tag":"token","characterOffsetEnd":"3","characterOffsetBegin":"0","id":"t0","form":"aaa"},{".tag":"token","characterOffsetEnd":"7","characterOffsetBegin":"4","id":"t1","form":"bbb"}]}]}]}]}]}; line: 1, column: 126]'. Completing with 500 Internal Server Error response.
```

**Comment by hiroshinoji** [comment]
For the first problem, the cause seems to be around spaces. I found `--data-urlencode` can process the above input `aaa bbb`. I'm now inspecting the way to handle general `data`... If you can use `@file` directive, I expect that can avoid the newline problem in `--data-urlencode`.

For the second problem, it is a bug in JSON outputs, which I issued in #59. This can be avoided when the output format is xml. We will fix this soon.

**Comment by hiroshinoji** [comment]
Oops I forgot to mention that the reason why the above newline problem occurs only in English is that the default sentence splitter in `corenlp` does not regard newline characters as a sentence break in general. This is to handle broader, uncleaned input text.

If your input text is cleaned so that newline character is always a sentence break, try setting `--data-rulencode corenlp.ssplit.newlineIsSentenceBreak=always`. The default value of this is `never`. Another option is `two`, which treats only successive newlines as a reliable indicator (useful for handling a document segmented into paragraphs).

**Comment by hiroshinoji** [comment]
It seems that all data sent to the server must be properly escaped following https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.
Since the previous version, which could not handle `--data-urlencoded` properly, did not cause this problem, there might be some way to work with both `data` containing spaces and `--data-urlencoded`, but it seems difficult for now.

The `data` can be sent if every space is replace with `+`. Hence instead of `--data aaa bbb`, `--data aaa+bbb` works. If the JSON problem above is fixed, you can send an input containing both space and newline by escaping both, e.g., `aaa+bbb%0Accc`. This, or using `--data-urlencoded` seems the only solution currently available.

**Comment by JSB97** [comment]
I am not sure `--data-urlencode` is really the way to go since, as [issue 57](https://github.com/mynlp/jigg/issues/57) shows, jigg cannot handle the the new line literal '\n' internally for JP.

For EN, `--data-urlencode corenlp.ssplit.newlineIsSentenceBreak=always` certainly helps though.

**Comment by hiroshinoji** [comment]
I found that `echo "text" | curl --data-urlencode @- ` method can now eat very long text, such as that in #50:

```
echo "　【ニューヨーク＝清水石珠実】「世紀の合併」と言われながら失敗した米メディア大手タイムワーナーとネット大手ＡＯＬの統合から15年。そのタイムワーナーを通信大手ＡＴ ＆Ｔが買収することで、米国で業種を超えたメディア再編がまた動き出した。背景にはスマートフォン（スマホ）を通じたインターネット動画の普及がある。通信とメディア業界の境界線はこれまで以 上に薄まっている。 　ネット動画を巡る異業種間合併の先駆けは2011年の米ケーブルテレビ最大手コムキャストによるＮＢＣユニバーサルの買収だ。ネット配信するコンテンツの拡充が目的で、コムキャストは今年６月にも米アニメ制作大手のドリームワークス・アニメーションを傘下に収めた。 　ＡＴ＆Ｔが狙うのもコムキャスト型のビジネスモデルで、垂直統合による複合メディア化は両社を軸に進む。 　ＡＴ＆Ｔは15年に米プロフットボールリーグ（ＮＦＬ）など人気番組の放映権を持つ衛星テレビ大手のディレクＴＶを485億ドル（約５兆円）で買収。電話契約者の頭打ちが予想される中、総 売上高の３割強を占めるエンターテインメント事業の拡充を進めてきた。 　ランドール・スティーブンソン最高経営責任者（ＣＥＯ）は「世界的に優れたコンテンツを映画、テレビ、モバイル端末すべてで提供できるようになる」と買収の意義を述べた。スマホの付加価値を高め動画がもたらす広告収入も増やす考え。 　タイムワーナーも通信大手と組む事情がある。近年はネットフリックスやアマゾン・ドット・コムなど定額課金でネット動画の配信を扱うシリコンバレーの新興企業が台頭。こうした企業が独自番組の配信も始めた結果、ケーブルテレビの契約が減っている。多様化する番組配信へ の対応は急務だった。 　さらに20年ごろには「５Ｇ」と呼ばれる毎秒10ギガ（ギガは10億）ビットの通信速度を持つ携帯電話の無線通信規格が実用化される見込み。ネット動画配信の市場が拡大するのは確実で、買収を後押ししたとみられる。 　ただ課題もある。タイムワーナーは01年にインターネット大手ＡＯＬと経営統合したが、09年には合併を解消した。企業文化で折り合いがつかず、インターネットバブルの崩壊も影響した。異業種合併で成果をあげることは容易ではない。 　独禁当局の判断も注目だ。コンテンツがＡＴ＆Ｔに独占的に囲い込まれるのは米政府も望まない。コムキャストがＮＢＣユニバーサルを買収した際は、司法省と米連邦通信委員会の承認を得るのに１年以上かかった。米ニューヨーク・タイムズ紙はＡＴ＆Ｔが競合社向けにタイムワーナーのコンテンツ使用料をつり上 げる恐れを指摘する。 　22日午前には大統領選のトランプ候補が「一握りの会社にあまりにも権力が集中している」と買収に反対する考えを表明。政治リスクもある。 　それでも米メディア企業がか らむ業界再編の動きが後をたたない。 　放送業界では05年に分離したＣＢＳとバイアコムの再統合が取り沙汰される。タイムワーナーを巡っては米アップルも買収に興味を示したもよう。21世紀フォックスも数年前に買収を提案した。 　７月には米携帯首位のベライゾン・コミュニケーションズが米ヤフーの買収を決めた。傘下のネット大手ＡＯＬとの一体運営で、コンテンツ配信やデジタル広告事業の強化を目指す。 　「動画の未来はモバイル端末であり、モバイル端末の未来は動画だ」――。22日にＡＴ＆Ｔとタイムワーナーが出した記者発表文にはこんな言葉が盛り込まれた。通信とメディアの融合は今後も続きそうな気配だ。 　ＡＴ＆Ｔ　電話を発明したグラハム・ベルの電話会社を源流とする米通信大手。業界２位の米携帯業界で飽和感が強まるなか、買収を通じて「海外」「娯楽」分野を強化している。この２年間でメキシコの携帯大手２社や米衛星放送大手ディレクＴＶを買収した。競合する米携帯最大手ベライゾン・コミュニケーションズが買収で合意したヤフーのネット事業にも関心 を示していた。本社はテキサス州ダラス。2015年12月通期の売上高は1468億ドル、純利益は133億ドル。 　タイムワーナー　1990年に米映画会社ワーナー・ブラザーズの親会社が出版大手タイムを買収 して誕生した。「セックス・アンド・ザ・シティ」など人気ドラマの製作で定評のある有料テレビ局「ＨＢＯ」やニュース専門局「ＣＮＮ」も傘下に抱える。2001年、インターネット大手アメリカ・オ ンライン（ＡＯＬ）に買収されたが、相乗効果を生み出せず09年に分離。動画コンテンツ事業に特化するため14年には出版部門タイムも切り離した。15年12月通期の売上高は281億ドル、純利益は38億ドル。本社はニューヨーク市。" | curl "http://localhost:8080/annotate?outputFormat=json&annotators=ssplit%2Cmecab" --data-urlencode @- --data-urlencode "nThreads=1"
```

The reason the previous server cannot handle this was that the previous python server failed to send the larger text. Maybe there is some buffer size limit, but I wonder it is also the case when specifying text directly in `--data q=text` or `--data-urlencode q=text`? `echo` does not seem to cause special problems.

In this way `\n` in text is recognized as a newline, e.g.:
```
echo "aaa\nbbb" | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode "annotators=corenlp[tokenize,ssplit]" --data-urlencode @- --data-urlencode "nThreads=1"
```
works as expected.

**Comment by hiroshinoji** [comment]
Seems solved.
