### ISSUE TITLE
Add syncha to pipeline

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#67]
Just wondering if adding [syncha](https://sites.google.com/site/ryuiida/syncha) was on the enhancement list, given the lack of coreference resolvers for JP?

**Comment by hiroshinoji** [comment]
Adding a pred-arg analyzer connected with mecab/cabocha is in the to-do list, but not supported yet.

Now `knp` is the only tool that can output pred-arg structures. This provides a bunch of other analyses jointly, such as coreferences, cases, etc. But it only assumes tokenization with JUMAN instead of mecab, which means analyses are based on different dictionaries.

We planned to add chapas (#8) instead of syncha, since it is in JVM. I remember we partly developed the annotator of that, but it was not finished. I will resume it soon.
