### ISSUE TITLE
Sentence split exceptions

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#72]
I want to run a dependency parse over the below;
> 北越銀行の久須美隆頭取は「日本経済は先行きに不透明感が増しており、景気回復の持続へ試練の時を迎えている。地域活性化に向けての努力が大事」と述べた。

Prior to running the dependency parser, Jigg splits sentences based on the position of "。"
> 北越銀行の久須美隆頭取は「日本経済は先行きに不透明感が増しており、景気回復の持続へ試練の時を迎えている。
> 地域活性化に向けての努力が大事」と述べた。

which results in two sentences being parsed separately.

Is it possible to avoid this?

**Comment by hiroshinoji** [comment]
This is actually a harder problem in current Japanese NLP, though it seems intuitively simple. Also related to #44.

Since the current `ssplit` is just based on a simple regular expression, it cannot recognize that the current position is inside some quotes (「 and 」). Machine learning-based approach might alleviate this, but it needs to capture a relatively global context.

Maybe one reasonable solution is to extend the current rule-based system to handle such special cases by adding some heuristics, e.g., do not recognize 。 as a splitter when an open quote is found on the left.
